### ISSUE TITLE
Inquiring about something I couldn't understand

### ISSUE THREAD

**Issue by ghadooo** [microchip-pic-avr-examples/attiny3217-qt8-touch-surface-example-studio#1]
In "led_driver.c" specifically this function where I added my questions in comments:
**_void led_decode_position(void)
{
	uint8_t h_pos = 0, v_pos = 0;
	led_reset();

	if (qtm_surface_cs_control1.qtm_surface_contact_data->qt_contact_status) {
		h_pos = (qtm_surface_cs_control1.qtm_surface_contact_data->h_position / 43); // why did we devide by 43 here?
		h_pos = (1 << (5 - h_pos)); // what does this substraction in the shifting mean?
		led_gpio_update(h_pos, LED_HOR);

		v_pos = (qtm_surface_cs_control1.qtm_surface_contact_data->v_position / 52); // why did we devide by 52 here?
		v_pos = (1 << (4 - v_pos));
		led_gpio_update(v_pos, LED_VER); // what does this substraction in the shifting mean?
	}
}_**

**Comment by SeanConlonIRE** [comment]
The division was used to tune position to trigger points on the LEDS.
When looking at h_pos with a breakpoint you can see that the value can be in the hundreds from the h_position parameter of the struct.
e.g. 229/43 =5 identifies which horizontal LED(1-5) should activate to indicate the position.
Same is true for v_position/52 in the vertical.
These numbers were obtained by tuning and placing finger in different positions on the sensor.

h_pos and v_pos information is then sent to the LED driver IC (MCP23017 ) on the QT8 via I2C.
The shift and subtract converts the LED we want to drive into its corresponding IO Line on the  MCP23017.
For more info, have a look at the MCP23017 datasheet and the function  void led_gpio_update(uint8_t data, uint8_t ver_or_hor)
The OLATA and OLATB registers are being used on the MCP23017.

**Comment by pic-avr-github-admin** [comment]
Closing this issue as no follow-up questions were asked.
